spring:
  application:
    name: bushub-discovery

  config:
    # not working with docker compose, so the config server is explicitly set here
    import: optional:configserver:http://172.17.0.1:9000/config


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # sample translation: http://localhost:9003/discovery
      default-zone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}

#------------------------------------
# Server settings
#------------------------------------
server:
  port: 9003
  servlet:
    context-path: /discovery