server:
  port: 9200
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  servlet:
    context-path: /config

spring:
  application:
    name: bushub-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/thepipeman/bushub-cloud-config
          default-label: main
          clone-on-start: true
          force-pull: true
          timeout: 10
          search-paths: bushub*