spring:
  application:
    name: bushub-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/thepipeman/bushub-configuration
          skip-ssl-validation: true

#------------------------------------
# Server settings
#------------------------------------

server:
  port: 9000
  servlet:
    context-path: /api
