version: '3.9'

services:
  bushub-config:
    image: bushub/bushub-config:0.0.1-SNAPSHOT
    container_name: bushub-config
    ports:
      - 9000:9000
    networks:
      backend:
        aliases:
          - "bushub-config"

  bushub-core:
    depends_on:
      bushub-config:
        condition: service_started
    restart: on-failure
    image: bushub/bushub-core:0.0.1-SNAPSHOT
    container_name: bushub-core
    ports:
      - 9003:9003
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://172.17.0.1:9000/api

    networks:
      - backend


networks:
  backend:
    driver: bridge