spring:
  application:
    name: bushub-gateway

  config:
    # not working with docker compose, so the config server is explicitly set here
    import: optional:configserver:http://172.17.0.1:9000/config

  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: bushub-core
          uri: lb://bushub-core
          predicates:
            - Path=/core/**
          filters:
            - RewritePath=/core/(?<path>.*), /$\{path}
        - id: bushub-booking
          uri: lb://bushub-booking
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.1:9001/eureka

#------------------------------------
# Server settings
#------------------------------------
server:
  port: 9002
