server:
  servlet:
    context-path: /api
  port: 9300


spring:
  application:
    name: bushub-core

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/bushub_core
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhc-pool

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: false
    mixed: true
    out-of-order: true
    table: schema_version


logging:
  ignore-get-requests: true
  shorten-stacktrace: true
  log-request-details-on-error: true
  pattern:
    console: "%clr(%d){faint} %clr(%level) [%clr(%X{requestId}){magenta}] %clr(%logger{35}){cyan}: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %level [%X{requestId}][%clr(%X{sid}){boldGreen}] %logger{35}: %msg%n"