spring:
  config:
    # not working with docker compose, so the config server is explicitly set here
    import: optional:configserver:http://localhost:9000/config


eureka:
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka


logging:
  level:
    com.bushub: TRACE
