spring:
  application:
    name: bushub-booking

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/bushub_booking
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhc-pool

  # Flyway settings
  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: false
    mixed: true
    out-of-order: true
    table: schema_version

#  config:
#    # not working with docker compose, so the config server is explicitly set here
#    import: optional:configserver:http://172.17.0.1:9000/config
#
#  cloud:
#    config:
#      name: bushub-booking
#      fail-fast: true
#      retry:
#        initial-interval: 1000
#        max-interval: 2000
#        max-attempts: 20

#------------------------------------
# Server settings
#------------------------------------

server:
  port: 9004
  servlet:
    context-path: /api


feign:
  client:
    config:
      default:
        requestInterceptors:
          - com.bushub.booking.util.http.CustomHttpConfig
